version: '3.8'

services:
  bio-service:
    build: .
    container_name: bio-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./service2.db
    volumes:
      - ./service2.db:/app/service2.db
    restart: unless-stopped